name: LPX
main: space.commandf1.cracker.lpx.LPXCrackerPlugin
authors:
  - Ytnoos
  - commandf1
version: 3.7.6
api-version: 1.13
description: Blazingly stable anti exploit 1.8-1.21 but cracked
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
folia-supported: true
commands:
  lpx:
    description: Main command
